// src/app/components/account/account.component.ts
import { Component, OnDestroy, OnInit, ViewChild } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { NgbDateAdapter, NgbDateNativeAdapter, NgbModal } from '@ng-bootstrap/ng-bootstrap';
import { Store } from '@ngrx/store';
import { Account } from 'src/app/models/account';
import { Category } from 'src/app/models/category';
import { Transaction } from 'src/app/models/transaction';
import { CategoryDataService } from 'src/app/services/category-data.service';
import { TransactionDataService } from 'src/app/services/transaction-data.service';
import { DeleteConfirmationModalComponent } from 'src/app/shared/delete-confirmation-modal/delete-confirmation-modal.component';
import { AddTransactionDialogComponent } from './add-transaction-dialog/add-transaction-dialog.component';
import { accounts, State } from 'src/app/state';
import { Subscription } from 'rxjs/internal/Subscription';
import { AppActions } from 'src/app/state/actions';

@Component({
  selector: 'app-account',
  templateUrl: './account.component.html',
  styleUrls: ['./account.component.css'],
  providers: [{provide: NgbDateAdapter, useClass: NgbDateNativeAdapter}]
})
export class AccountComponent implements OnInit, OnDestroy {
  @ViewChild('addTransactionDialog') addTransactionDialog!: AddTransactionDialogComponent;
  account: Account | null = null;
  accounts: Array<Account> | null = null;
  transactions: Array<Transaction> = [];
  categories: Array<Category> = [];
  editTransaction: Transaction = {} as Transaction;
  isAddDialogVisible = false;
  isEditingRow = false;

  private isAccountsLoading = false;
  private isTransactionsLoading = false;
  private isCategoriesLoading = false;

  private subscriptions: Subscription[] = [];

  constructor(private route: ActivatedRoute,
              private store: Store<State>,
              private modalService: NgbModal,
              private categoryDataService: CategoryDataService,
              private transactionDataService: TransactionDataService) { }

  ngOnInit(): void {
    this.store.dispatch(AppActions.setIsLoading({ isLoading: true }));

    this.isAccountsLoading = true;
    this.subscriptions.push(this.store.select(accounts).subscribe(accounts => {
      this.accounts = accounts;

      this.route.params.subscribe(params => {
        this.store.dispatch(AppActions.setIsLoading({ isLoading: true }));
        if (params.account) {
          this.account = accounts.find(account => account.url === params.account) ?? null;

          if(this.account) {
            this.isTransactionsLoading = true;

            this.transactionDataService.getByAccount(this.account.id).subscribe(transactions => {
              this.transactions = transactions
                .map(transaction => ({ ...transaction, date: new Date(transaction.date)}))
                .sort((a, b) => b.date.getTime() - a.date.getTime());
              this.isTransactionsLoading = false;
              this.setIsLoading();
            }, error => {
              this.isTransactionsLoading = false;
              this.setIsLoading();
              console.error(error);
            });
          }
        } else {
          this.account = null;
          this.isTransactionsLoading = true;
          this.transactionDataService.get().subscribe(transactions => {
            this.transactions = transactions
              .map(transaction => ({ ...transaction, date: new Date(transaction.date)}))
              .sort((a, b) => b.date.getTime() - a.date.getTime());
            this.isTransactionsLoading = false;
            this.setIsLoading();
          }, error => {
            this.isTransactionsLoading = false;
            this.setIsLoading();
            console.error(error);
          });
        }
      });
      this.isAccountsLoading = false;
      this.setIsLoading();
    }, error => {
      this.isAccountsLoading = false;
      this.setIsLoading();
    }));
    this.categoryDataService.getSimple().subscribe(categories => {
      this.categories = categories;
      this.isCategoriesLoading = false;
      this.setIsLoading();
    }, error => {
      this.isCategoriesLoading = false;
      this.setIsLoading();
      console.error(error);
    });
  }

  ngOnDestroy(): void {
    this.subscriptions.forEach(subscription => subscription.unsubscribe());
  }

  setIsLoading(): void {
    if (!this.isAccountsLoading && !this.isCategoriesLoading && !this.isTransactionsLoading) {
      this.store.dispatch(AppActions.setIsLoading({ isLoading: false }));
    }
  }

  getCategoryName(id: number): string {
    const category = this.categories.find(c => c.id === id);
    return category ? category.name : '';
  }

  getAccountName(id: number): string {
    const account = this.accounts?.find(a => a.id === id);
    return account ? account.name : '';
  }

  convertToMoney(event: any, transaction: Transaction): void {
    if (!event.target.value) { return; }

    transaction.cost = Math.round(event.target.value * 100) / 100;

    event.target.value = transaction.cost;
  }

  startEditing(transaction: Transaction): any {
    const unsavedTransaction = this.transactions.find(t => t.isEditing);
    if (unsavedTransaction) {
      this.cancelEditing(unsavedTransaction);
    }
    this.editTransaction = { ...transaction } as Transaction;
    transaction.isEditing = true;
  }

  cancelEditing(transaction: Transaction): void {
    transaction.isEditing = false;
  }

  save(transaction: Transaction): void {
    this.store.dispatch(AppActions.setIsLoading({ isLoading: true }));
    this.transactionDataService.update(transaction).subscribe(updatedTransaction => {
      const transactionIndex = this.transactions.findIndex(t => t.id === updatedTransaction.id);
      this.transactions[transactionIndex] = updatedTransaction;
      this.sortTransactions();
      transaction.isEditing = false;
      this.isEditingRow = false;
      this.store.dispatch(AppActions.setIsLoading({ isLoading: false }));
    }, error => {
      this.store.dispatch(AppActions.setIsLoading({ isLoading: false }));
      console.error(error);
    });
  }

  confirmDelete(transaction: Transaction): void {
    const modal = this.modalService.open(DeleteConfirmationModalComponent);
    modal.componentInstance.title = 'Delete Transaction';
    modal.componentInstance.message = 'Would you like to delete this Transaction?';
    modal.result.then(result => {
      if (result) {
        this.delete(transaction);
      }
    }, () => { });
  }

  delete(transaction: Transaction): void {
    this.transactionDataService.delete(transaction.id).subscribe(() => {
      this.transactions.splice(this.transactions.findIndex(t => t.id === transaction.id), 1);
    });
  }

  sortTransactions(): void {
    this.transactions.sort((a, b) => b.date.getTime() - a.date.getTime());
  }

  showAddTransactionDialog(): void {
    const modal = this.modalService.open(AddTransactionDialogComponent);
    modal.result.then((transaction: Transaction) => {
      this.transactions.push(transaction);
      this.sortTransactions();
    });
  }
}

<div class="flex-column">
  <span class="flex-row transaction-header-row">
    <h2>{{ account ? account.name : "All Accounts" }}</h2>
    <button type="button"
            class="btn btn-primary button-icon add-transaction-button"
            (click)="addTransactionDialog.show()">
      <i class="bi bi-plus icon-button"></i>
    </button>
  </span>
  <table class="table outer-border-table">
    <colgroup>
      <col style="width: 15%; min-width: 175px;">
      <col *ngIf="!account" style="width: 20%">
      <col style="width: 25%">
      <col style="width: 20%">
      <col style="width: 15%; min-width: 110px;">
      <col style="width: 25%">
      <col style="width: 50px">
    </colgroup>
    <thead class="thead-dark">
      <tr>
        <th>Date</th>
        <th *ngIf="!account">Account</th>
        <th>Recipient</th>
        <th>Category</th>
        <th class="text-align-right">Cost</th>
        <th>Tags</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <tr *ngFor="let transaction of transactions">
        <td>
          <div *ngIf="transaction.isEditing">
            <div class="input-group">
              <input ngbDatepicker
                    id="date"
                    type="text"
                    placeholder="yyyy/MM/dd"
                    [(ngModel)]="editTransaction.date"
                    #datePicker="ngbDatepicker"
                    name="date"
                    class="form-control"
                    required>
              <div class="input-group-append">
                <button class="btn btn-dark bi-calendar-day"
                        (click)="datePicker.toggle()"
                        type="button"></button>
              </div>
            </div>
          </div>
          <div *ngIf="!transaction.isEditing">
            {{ transaction.date | date:'yyyy-MM-dd' }}
          </div>
        </td>
        <td *ngIf="!account">
          <div *ngIf="transaction.isEditing">
            <select id="account"
                    [(ngModel)]="editTransaction.accountId"
                    name="account"
                    class="form-control"
                    required>
              <option *ngFor="let acc of accounts" 
                      [value]="acc.id">{{ acc.name }}</option>
            </select>
          </div>
          <div *ngIf="!transaction.isEditing">
            {{ getAccountName(transaction.accountId) }}
          </div>
        </td>
        <td>
          <div *ngIf="transaction.isEditing">
            <input id="recipient"
                  type="text"
                  [(ngModel)]="editTransaction.recipient"
                  #recipient="ngModel"
                  name="recipient"
                  class="form-control"
                  required>
          </div>
          <div *ngIf="!transaction.isEditing">
            {{ transaction.recipient }}
          </div>
        </td>
        <td>
          <div *ngIf="transaction.isEditing">
            <select id="category"
                    [(ngModel)]="editTransaction.categoryId"
                    name="category"
                    class="form-control"
                    required>
              <option *ngFor="let category of categories" 
                      [value]="category.id">{{ category.name }}</option>
            </select>
          </div>
          <div *ngIf="!transaction.isEditing">
            {{ getCategoryName(transaction.categoryId) }}
          </div>
        </td>
        <td>
          <div *ngIf="transaction.isEditing">
            <input id="cost"
                  [ngModel]="editTransaction.cost"
                  (blur)="convertToMoney($event, editTransaction)"
                  (keyup.enter)="convertToMoney($event, editTransaction)"
                  name="cost"
                  class="form-control"
                  style="text-align: right;"
                  required>
          </div>
          <div *ngIf="!transaction.isEditing" class="text-align-right">
            {{ transaction.cost | currency: 'USD' }}
          </div>
        </td>
        <td>
        </td>
        <td class="icons-cell">
          <div class="icons-container">
            <button *ngIf="!transaction.isEditing" 
                    type="button" 
                    class="cell-button-icon cell-button-icon-primary" 
                    (click)="startEditing(transaction)">
              <i class="bi-pencil text-primary"></i>
            </button>
            <button *ngIf="!transaction.isEditing" 
                    type="button" 
                    class="cell-button-icon cell-button-icon-danger"
                    (click)="confirmDelete(transaction)">
              <i class="bi-trash text-danger"></i>
            </button>
            <button *ngIf="transaction.isEditing" 
                    type="button" 
                    class="cell-button-icon cell-button-icon-success" 
                    (click)="save(editTransaction)">
              <i class="bi-check-circle text-success"></i>
            </button>
            <button *ngIf="transaction.isEditing" 
                    type="button" 
                    class="cell-button-icon cell-button-icon-secondary" 
                    (click)="cancelEditing(transaction)">
              <i class="bi-x-circle text-secondary"></i>
            </button>
          </div>
        </td>
      </tr>
    </tbody>
  </table>
</div>

<app-add-transaction-dialog #addTransactionDialog
                            [defaultAccount]="account"
                            (save)="onNewTransaction($event)"></app-add-transaction-dialog>

// web/src/components/account/Account.vue
<template>
  <div class="flex-column">
    <span class="flex-row transaction-header-row">
      <h2>{{ account ? account.name : "All Accounts" }}</h2>
      <button type="button"
              class="btn btn-primary button-icon add-transaction-button"
              @click="showAddTransactionDialog()">
        <i class="bi bi-plus-lg icon-button"></i>
      </button>
    </span>
    <table class="table table-dark">
      <colgroup>
        <col style="width: 15%; min-width: 175px;">
        <col v-if="!account" style="width: 20%">
        <col style="width: 25%">
        <col style="width: 20%">
        <col style="width: 15%; min-width: 110px;">
        <col style="width: 25%">
        <col style="width: 50px">
      </colgroup>
      <thead class="thead-dark">
        <tr>
          <th>Date</th>
          <th v-if="!account">Account</th>
          <th>Recipient</th>
          <th>Category</th>
          <th class="text-align-right">Cost</th>
          <th>Tags</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="transaction in transactions"
            :key="transaction.id">
          <td>
            <div v-if="transaction.isEditing">
              <input class="form-control"
                      type="date"
                      name="date"
                      v-model="editTransaction.date"
                      placeholder="yyyy/MM/dd"
                      required />
            </div>
            <div v-if="!transaction.isEditing">
              {{ $filters.toShortDate(transaction.date)}}
            </div>
          </td>
          <td v-if="!account">
            <div v-if="transaction.isEditing">
              <select id="account"
                      v-model="editTransaction.accountId"
                      name="account"
                      class="form-control"
                      required>
                <option v-for="acc in accounts"
                        :key="acc.id"
                        :value="acc.id">{{ acc.name }}</option>
              </select>
            </div>
            <div v-if="!transaction.isEditing">
              {{ getAccountName(transaction.accountId) }}
            </div>
          </td>
          <td>
            <div v-if="transaction.isEditing">
              <input id="recipient"
                    type="text"
                    v-model="editTransaction.recipient"
                    name="recipient"
                    class="form-control"
                    required>
            </div>
            <div v-if="!transaction.isEditing">
              {{ transaction.recipient }}
            </div>
          </td>
          <td>
            <div v-if="transaction.isEditing">
              <select id="category"
                      v-model="editTransaction.categoryId"
                      name="category"
                      class="form-control"
                      required>
                <option v-for="category in categories"
                        :key="category.id" 
                        :value="category.id">{{ category.name }}</option>
              </select>
            </div>
            <div v-if="!transaction.isEditing">
              {{ getCategoryName(transaction.categoryId) }}
            </div>
          </td>
          <td>
            <div v-if="transaction.isEditing">
              <input id="cost"
                     v-model="editTransaction.cost"
                     @blur="convertToMoney($event, editTransaction)"
                     @keyup.enter="convertToMoney($event, editTransaction)"
                     name="cost"
                     class="form-control text-align-right"
                     required>
            </div>
            <div v-if="!transaction.isEditing" class="text-align-right">
              {{ $filters.toCurrency(transaction.cost) }}
            </div>
          </td>
          <td>
          </td>
          <td class="icons-cell">
            <div class="icons-container">
              <button v-if="!transaction.isEditing" 
                      type="button" 
                      class="cell-button-icon cell-button-icon-primary" 
                      @click="startEditing(transaction)">
                <i class="bi-pencil text-primary"></i>
              </button>
              <button v-if="!transaction.isEditing" 
                      type="button" 
                      class="cell-button-icon cell-button-icon-danger"
                      @click="confirmDelete(transaction)">
                <i class="bi-trash text-danger"></i>
              </button>
              <button v-if="transaction.isEditing" 
                      type="button" 
                      class="cell-button-icon cell-button-icon-success" 
                      @click="save(editTransaction)">
                <i class="bi-check-circle text-success"></i>
              </button>
              <button v-if="transaction.isEditing" 
                      type="button" 
                      class="cell-button-icon cell-button-icon-secondary" 
                      @click="cancelEditing(transaction)">
                <i class="bi-x-circle text-secondary"></i>
              </button>
            </div>
          </td>
        </tr>
      </tbody>
    </table>
  </div>

  <DeleteConfirmation ref="deleteConfirmationModal" />
  <TransactionDialog ref="transactionDialog" />
</template>

<script>
import { mapState } from 'vuex'
import DeleteConfirmation from '../shared/DeleteConfirmation.vue'
import TransactionDialog from './TransactionDialog.vue'

export default {
  name: 'Account',
  components: {
    DeleteConfirmation,
    TransactionDialog
  },
  computed: {
    ...mapState({
      account: state => state.accounts.account,
      accounts: state => state.accounts.all,
      categoryGroups: state => state.categoryGroups.all,
      categories: state => state.categories.all,
      transactions: state => state.transactions.all
    })
  },
  data () {
    return {
      isEditingRow: false,
      editTransaction: null,
      renameText: '',
      accountUrl: null
    }
  },
  methods: {
    getCategoryName (id) {
      const category = this.categories.find(c => c.id === id)
      return category ? category.name : ''
    },

    getAccountName (id) {
      const account = this.accounts?.find(a => a.id === id)
      return account ? account.name : ''
    },

    convertToMoney (event, transaction) {
      if (!event.target.value) { return }

      transaction.cost = Math.round(event.target.value * 100) / 100

      event.target.value = transaction.cost
    },

    startEditing (transaction) {
      const unsavedTransaction = this.transactions.find(t => t.isEditing)
      if (unsavedTransaction) {
        this.cancelEditing(unsavedTransaction)
      }
      this.editTransaction = { ...transaction }
      transaction.isEditing = true
    },

    cancelEditing (transaction) {
      transaction.isEditing = false
    },

    async save (transaction) {
      this.$store.commit('setIsLoading', true)
      const updatedTransaction = await this.$store.dispatch('transactions/update', transaction)

      const transactionIndex = this.transactions.findIndex(t => t.id === updatedTransaction.id)
      this.transactions[transactionIndex] = updatedTransaction
      this.sortTransactions()
      transaction.isEditing = false
      this.isEditingRow = false
    },

    confirmDelete (transaction) {
      if (this.$refs.deleteConfirmationModal && transaction) {
        this.$refs.deleteConfirmationModal.open(this.delete, transaction.id, null)
      }
    },

    async delete (transaction) {
      await this.$store.dispatch('transactions/delete', transaction.id)
      this.transactions.splice(this.transactions.findIndex(t => t.id === transaction.id), 1)
    },
    
    sortTransactions () {
      this.transactions.sort((a, b) => b.date.getTime() - a.date.getTime())
    },

    showAddTransactionDialog () {
      if (this.$refs.transactionDialog) {
        this.$refs.transactionDialog.open(this.account?.id)
      }
    }
  },
  mounted () {
    this.$store.dispatch('accounts/get')
    this.$watch(
      () => this.$route.params,
      () => {
        this.accountUrl = this.$route.params.url
        this.name = null
        this.description = null

        if (this.accountUrl) {
          this.$store.dispatch('accounts/find', this.accountUrl)
        } else {
          this.$store.commit('accounts/setAccount', null)
        }
      },
      { immediate: true }
    )
  },
  watch: {
    account (value) {
      if (value) {
        this.$store.dispatch('transactions/getByAccount', value.id)
      } else {
        this.$store.dispatch('transactions/get')
      }
    }
  }
}
</script>

<style scoped lang="scss">
  .transaction-header-row {
    justify-content: space-between;
  }

  .add-transaction-button {
    align-self: center;
    margin: 0.5em 0;
  }
</style>
